// MOCKED DATA - Saffron Brand Consultants "Work" page clone
// Real project imagery pulled from Saffron's public imgix CDN for design fidelity.

const ix = (u) => u; // images already carry imgix params

export const PROJECTS = [
  {
    id: "cupra",
    client: "Cupra",
    industry: ["Mobility & Hospitality"],
    region: "Europe",
    services: ["Brand Identity", "Brand Positioning"],
    title: "The impulse of a new generation",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_3.1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra_Icon.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "meta",
    client: "Meta",
    industry: ["Technology"],
    region: "Americas",
    services: ["Brand Architecture", "Experience Ecosystem"],
    title: "The next chapter of social connection",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "galp",
    client: "Galp",
    industry: ["Energy & Industrial"],
    region: "Europe",
    services: ["Brand Identity", "Delivery System"],
    title: "Evolving energy for life",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_1_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_2_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_3_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_4_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_5_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Icon.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "play",
    client: "Play Media",
    industry: ["Culture & Media"],
    region: "Europe",
    services: ["Brand Identity", "Customer Experience"],
    title: "Rewriting the rules of Play",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_P1_4x5_1_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_Gallery_2_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_Gallery_3_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_Gallery_4_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_Gallery_5_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play_Icon_Avatar_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "blue-car-rental",
    client: "Blue Car Rental",
    industry: ["Mobility & Hospitality"],
    region: "Europe",
    services: ["Brand Identity", "Brand Positioning"],
    title: "Discovering the road to Iceland",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_1_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_2_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_3_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_4_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_5_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "zelestra",
    client: "Zelestra",
    industry: ["Energy & Industrial"],
    region: "Europe",
    services: ["Brand Positioning", "Brand Identity"],
    title: "Powering progress with purpose",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_1_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_2_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_3_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_4_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_5_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Icon.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "art-basel-zero-10",
    client: "Art Basel",
    industry: ["Culture & Media"],
    region: "Europe",
    services: ["Experience Ecosystem", "Prototype"],
    title: "Expanding Art Basel into the digital era",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_1.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_2.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_3.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_4.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_5.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Art-Basel_Zero-10_Icon.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "west-japan-railway-company",
    client: "West Japan Railway Company",
    industry: ["Mobility & Hospitality", "Places & Real Estate"],
    region: "Asia",
    services: ["Brand Architecture", "Customer Experience"],
    title: "The extraordinary in plain sight",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Cover_1.2.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Hover_3.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Hover_4.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Hover_5.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Cover_1.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-Wes_Avatar.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "mobily",
    client: "Mobily",
    industry: ["Technology", "Telecommunications"],
    region: "Middle East",
    services: ["Brand Positioning", "Brand Identity"],
    title: "Saudi\u2019s challenger. Supercharged.",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_1_h.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_Icon_Avatar_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "amazon-ads",
    client: "Amazon Ads",
    industry: ["Technology"],
    region: "Americas",
    services: ["Brand Identity", "Experience Ecosystem"],
    title: "The rise of Ads",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_2.2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Icon_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "alphasense",
    client: "AlphaSense",
    industry: ["Technology"],
    region: "Americas",
    services: ["Brand Positioning", "Brand Identity"],
    title: "The future of decision-making",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "repsol",
    client: "Repsol",
    industry: ["Energy & Industrial"],
    region: "Europe",
    services: ["Brand Architecture", "Delivery System"],
    title: "Confluence of energies",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "radio-1",
    client: "VRT",
    industry: ["Culture & Media"],
    region: "Europe",
    services: ["Brand Identity", "Customer Experience"],
    title: "Essential Listening",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Cover_IMG_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Icon_1x1_v3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "youtube",
    client: "YouTube",
    industry: ["Technology"],
    region: "Americas",
    services: ["Brand Architecture", "Experience Ecosystem"],
    title: "Taking the tube out of YouTube",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Cover_IMG_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "gulf-air",
    client: "Gulf Air",
    industry: ["Mobility & Hospitality"],
    region: "Middle East",
    services: ["Brand Identity", "Customer Experience"],
    title: "Reawakening the original Middle Eastern airline",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
];

export const FILTERS = {
  region: ["Europe", "Americas", "Middle East", "Asia"],
  industry: [
    "Mobility & Hospitality",
    "Energy & Industrial",
    "Culture & Media",
    "Technology",
    "Telecommunications",
    "Places & Real Estate",
  ],
  service: [
    "Brand Architecture",
    "Brand Identity",
    "Brand Positioning",
    "Business Case",
    "Customer Experience",
    "Delivery System",
    "Employee Experience",
    "Experience Ecosystem",
    "Prototype",
  ],
};

export const NAV_LINKS = [
  { label: "Work", href: "#", active: true },
  { label: "About", href: "#" },
  { label: "Journal", href: "#" },
  { label: "Lab", href: "#" },
  { label: "Careers", href: "#", badge: 1 },
  { label: "Contact", href: "#" },
];
