// GEMOCKTE DATA - Kloon van de "Werk"-pagina van Saffron Brand Consultants
// Echte projectbeelden via Saffron's publieke imgix-CDN voor visuele getrouwheid.

const ix = (u) => u; // afbeeldingen bevatten al imgix-parameters

export const PROJECTS = [
  {
    id: "cupra",
    client: "Cupra",
    industry: ["Mobiliteit & Horeca"],
    region: "Europa",
    services: ["Merkidentiteit", "Merkpositionering"],
    title: "De impuls van een nieuwe generatie",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_3.1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra-CS_Hover_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Cupra_CS/Gallery/Cupra_Icon.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "meta",
    client: "Meta",
    industry: ["Technologie"],
    region: "Amerika",
    services: ["Merkarchitectuur", "Ervaringsecosysteem"],
    title: "Het volgende hoofdstuk van sociale verbinding",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Hover_IMG_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Meta_CS/Meta_MBS/Gallery/Meta_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "galp",
    client: "Galp",
    industry: ["Energie & Industrie"],
    region: "Europa",
    services: ["Merkidentiteit", "Leveringssysteem"],
    title: "Energie die meegroeit met het leven",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_1_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_2_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_3_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_4_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Gallery_5_4x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Galp_CS/Gallery/Galp_CS_Icon.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "play",
    client: "Play Media",
    industry: ["Cultuur & Media"],
    region: "Europa",
    services: ["Merkidentiteit", "Klantervaring"],
    title: "De regels van Play herschrijven",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_P1_4x5_1_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_Gallery_2_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_Gallery_3_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_Gallery_4_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play-Media_CS_Gallery_5_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Play-Media_CS/Gallery/Play_Icon_Avatar_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "blue-car-rental",
    client: "Blue Car Rental",
    industry: ["Mobiliteit & Horeca"],
    region: "Europa",
    services: ["Merkidentiteit", "Merkpositionering"],
    title: "De weg naar IJsland ontdekken",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_1_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_2_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_3_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_4_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_1x1_Hover_5_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Blue-Car_CS/Gallery/Blue-Car_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "zelestra",
    client: "Zelestra",
    industry: ["Energie & Industrie"],
    region: "Europa",
    services: ["Merkpositionering", "Merkidentiteit"],
    title: "Vooruitgang aandrijven met een doel",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_1_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_2_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_3_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_4_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Hover_5_3x.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Zelestra_CS/Gallery/Zelestra_Icon.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "art-basel-zero-10",
    client: "Art Basel",
    industry: ["Cultuur & Media"],
    region: "Europa",
    services: ["Ervaringsecosysteem", "Prototype"],
    title: "Art Basel uitbreiden naar het digitale tijdperk",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_1.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_2.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_3.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_4.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Zero-10_Hover_5.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Zero-10_CS/Gallery/Art-Basel_Zero-10_Icon.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "west-japan-railway-company",
    client: "West Japan Railway Company",
    industry: ["Mobiliteit & Horeca", "Locaties & Vastgoed"],
    region: "Azië",
    services: ["Merkarchitectuur", "Klantervaring"],
    title: "Het buitengewone in het volle zicht",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Cover_1.2.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Hover_3.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Hover_4.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Hover_5.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-West_Cover_1.webp?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/JR-West_CS/Gallery/JR-Wes_Avatar.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "mobily",
    client: "Mobily",
    industry: ["Technologie", "Telecommunicatie"],
    region: "Midden-Oosten",
    services: ["Merkpositionering", "Merkidentiteit"],
    title: "De uitdager van Saoedi-Arabië. Turbogeladen.",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_1_h.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_CS_Gallery_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Mobily_CS/Gallery-2/Mobily_Icon_Avatar_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "amazon-ads",
    client: "Amazon Ads",
    industry: ["Technologie"],
    region: "Amerika",
    services: ["Merkidentiteit", "Ervaringsecosysteem"],
    title: "De opkomst van Ads",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_2.2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Hover_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Amazon-Ads_CS/Gallery/AAds_Icon_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "alphasense",
    client: "AlphaSense",
    industry: ["Technologie"],
    region: "Amerika",
    services: ["Merkpositionering", "Merkidentiteit"],
    title: "De toekomst van besluitvorming",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Hover_IMG_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/AlphaSense_CS/Gallery/Alphasense_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "repsol",
    client: "Repsol",
    industry: ["Energie & Industrie"],
    region: "Europa",
    services: ["Merkarchitectuur", "Leveringssysteem"],
    title: "Samenvloeiing van energieën",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Hover_IMG_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Repsol_CS/Gallery/Repsol_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "radio-1",
    client: "VRT",
    industry: ["Cultuur & Media"],
    region: "Europa",
    services: ["Merkidentiteit", "Klantervaring"],
    title: "Essentieel luisteren",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Cover_IMG_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/VRT_Radio-1_CS/Gallery/Radio-1_Icon_1x1_v3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "youtube",
    client: "YouTube",
    industry: ["Technologie"],
    region: "Amerika",
    services: ["Merkarchitectuur", "Ervaringsecosysteem"],
    title: "De tube uit YouTube halen",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Cover_IMG_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Youtube_CS/Gallery/YouTube_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
  {
    id: "gulf-air",
    client: "Gulf Air",
    industry: ["Mobiliteit & Horeca"],
    region: "Midden-Oosten",
    services: ["Merkidentiteit", "Klantervaring"],
    title: "De oorspronkelijke Midden-Oosterse luchtvaartmaatschappij nieuw leven inblazen",
    images: [
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_2.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_3.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_4.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
      ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Hover_IMG_1x1_5.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&max-w=1200&ar=1%3A1&fit=crop"),
    ],
    icon: ix("https://saffron.imgix.net/Case-Studies/Gulf-Air_CS/Gallery/Gulf-Air_Icon_1x1.png?ixlib=js-3.8.0&q=75&auto=format%2Ccompress&w=64&h=64&max-w=3840"),
  },
];

export const FILTERS = {
  region: ["Europa", "Amerika", "Midden-Oosten", "Azië"],
  industry: [
    "Mobiliteit & Horeca",
    "Energie & Industrie",
    "Cultuur & Media",
    "Technologie",
    "Telecommunicatie",
    "Locaties & Vastgoed",
  ],
  service: [
    "Merkarchitectuur",
    "Merkidentiteit",
    "Merkpositionering",
    "Businesscase",
    "Klantervaring",
    "Leveringssysteem",
    "Medewerkerservaring",
    "Ervaringsecosysteem",
    "Prototype",
  ],
};
